name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, pdo_sqlite

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

      - name: Get commit author email
        id: author
        run: echo "::set-output name=email::$(git log -1 --pretty=format:'%ae')"

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build Failed
          body: Build failed for commit ${{ github.sha }}. Check the details at ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
          to: tongsreng@itc.edu.kh, ${{ steps.author.outputs.email }}
          from: leen4kie@gmail.com
